site_name: Normativa en ciberseguretat
site_description: Normativa en ciberseguretat para el módulo de ciberseguridad
site_author: Jose Luis Mas Cloquell
theme: readthedocs # O 'mkdocs'
nav:
  - Inici: index.md